name: Docker Build and HTML Serve

on: [push, pull_request]

jobs:
  docker-html-job:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Print basic info
      - name: Print System Info
        run: uname -a

      # Step 3: List Files
      - name: List Repo Files
        run: ls -alh

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-html-app .

      # Step 5: Run Docker Container
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 --name html-server my-html-app

      # Step 6: Verify Docker Container Running
      - name: Docker PS
        run: docker ps
